### PR TITLE
Feature/go kosu/lite client

### PR DESCRIPTION
**Pull request by gchaincl**
## Overview
This implements a basic Lite Client. The LiteClient is implemented as a RPC Client (`./abci/lite.go`) and also as a Proxy sub-command (`./cmd/kosulite/`) so that `./kosu-cli` can use the lite client proxy as an endpoint.

This PR also includes fixes a `./kosu-cli` bug and it restructures the Query Path adding the `./store/` prefix, this change was required to make the lite client works.

### CODE REVIEW

**Comment by hrharder** [comment]
This is great! Super cool that you can use the light client to serve the CLI.

How hard (/possible) would it be to serve the full JSONRPC over `kosulite`? Do you think that would take a lot of extra work?

Awesome that you got the proofs to work. Feel free to merge if you like, I wasn't sure if it was ready to or not.

**Comment by gchaincl** [comment]
We could definitively expose the JSON-RPC API using the `proxy.Wrapper` returned by `NewLite`, as it's a valid `rpcclient`.
Right now, you can `kosud rpc --url=http://lite` where lite is the address of `kosulite`.
How do you think we should expose it the user, would `kosud rpc --lite` makes sense so that the user just run a single command?

I'm not sure what would be the ideal scenario.

**Comment by hrharder** [comment]
Tagging as `[WIP]` just so I don't accidentally merge since the CI is passing.

**Comment by gchaincl** [comment]
@hrharder can you re-approve this one? I think it will be easier to merge it and then refactor the binaries

**Pull request merged**
