### PR TITLE
Refactor/ignoring generated go file

### PR DESCRIPTION
**Pull request by Freydal**
## Types of changes

-   [ ] Refactor/enhancement 
-   [ ] Bug fix/behavior correction 
-   [ ] New feature 
-   [ ] Breaking change 
-   [ ] Other, additional 

## Status

-   [ ] Prefix PR title with `[WIP]` if necessary (changes not yet made).
-   [ ] Add tests to cover changes as needed.
-   [ ] Update documentation/changelog as needed.
-   [ ] Verify all tests run correctly in CI and pass.
-   [ ] Ready for review/merge.

### CODE REVIEW

**Comment by Freydal** [comment]
@gchaincl (@hrharder too) Does this seem fine to remove this file from source control and just generate it?

**Review by qustavo — COMMENTED** [review]
In general, I avoid checking generated files to the VCS, generated files add noise to the history and they are big. In general, I don't think there is a single strategy and as usual, it depends.

In the case of protobuf, I've seen other projects checking the generated files [1], [2], [3], and I think that the main reason is consistency.

As a developer, I need to know that what I'm running on my machine is the exact same code that the one being run by other developers, by the CI tests and ultimately the code that is running in production.
Additionally, this also simplifies the building process as you probably won't need any extra step apart from getting the code and run it.

In any case, and as I mentioned above, I think it always depends and if you find a good reason to not check the files we should probably don't do it.

[1]: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api/apps/v1
[2]: https://github.com/grpc/grpc-go/tree/master/balancer/grpclb
[3]: https://github.com/lightningnetwork/lnd/blob/master/lnrpc/rpc.pb.go

**Comment by Freydal** [comment]
So in my opinion something needs to change, but it could alternatively be handled by removing automated execution of the generation.

I feel like generated code should either be:
1.  Selectively and intentionally generated and tracked within source control.
2. Routinely generated and  source assets tracked within source control.

I think an alternative would be removing the generation from the go-kosu/package.json build script.

**Comment by gchaincl** [comment]
> I think an alternative would be removing the generation from the go-kosu/package.json build script.
@Freydal would it make sense to move this generation to `//go:generate`?

**Comment by Freydal** [comment]
I believe it is go:generate that is being called.  Though the `build` script initiating the call is being called in the global mono repo build (which is possibly the right thing to do).

**Comment by hrharder** [comment]
@Freydal @gchaincl I don't have a strong opinion either way here, so am happy to let you two decide if you're able to come to an agreement. :) 

If not, let me know and I can help decide.

**Pull request closed without merging**
